apiVersion: v1
kind: Secret
metadata:
  name: miroir-secrets
  labels:
    app.kubernetes.io/part-of: miroir
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.db | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  MINIO_ROOT_USER: {{ .Values.minio.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.rootPassword | quote }}
